
server:
  port: 8760

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false     # 表明是eureka server
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/